# Use an official OpenJDK runtime
FROM eclipse-temurin:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file (Make sure to build the project first!)
COPY target/backend.jar app.jar

# Expose the backend's port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
